[package]
name = "solana-keygen"
description = "Solana key generation utility"
documentation = "https://docs.rs/solana-keygen"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "solana-keygen"
path = "src/keygen.rs"

[dependencies]
bs58 = { workspace = true, features = ["std"] }
clap = { version = "3.1.5", features = ["cargo"] }
dirs-next = { workspace = true }
num_cpus = { workspace = true }
serde_json = { workspace = true }
solana-clap-v3-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-derivation-path = { git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-instruction = { features = ["bincode"] , git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-keypair = { git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-message = { features = ["bincode"] , git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-pubkey = { default-features = false , git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-remote-wallet = { workspace = true, features = ["default"] }
solana-seed-derivable = { git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-signer = { git = "https://github.com/2501babe/solana-sdk.git", branch = "voteop" }
solana-version = { workspace = true }
tiny-bip39 = { workspace = true }

[dev-dependencies]
solana-pubkey = { workspace = true, features = ["rand"] }
tempfile = { workspace = true }
